// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AAvatar: typeof import("ant-design-vue/es")["Avatar"];
    AButton: typeof import("ant-design-vue/es")["Button"];
    ACard: typeof import("ant-design-vue/es")["Card"];
    ACardMeta: typeof import("ant-design-vue/es")["CardMeta"];
    ACheckbox: typeof import("ant-design-vue/es")["Checkbox"];
    AComment: typeof import("ant-design-vue/es")["Comment"];
    ADrawer: typeof import("ant-design-vue/es")["Drawer"];
    AEmpty: typeof import("ant-design-vue/es")["Empty"];
    AForm: typeof import("ant-design-vue/es")["Form"];
    AFormItem: typeof import("ant-design-vue/es")["FormItem"];
    AInput: typeof import("ant-design-vue/es")["Input"];
    AInputPassword: typeof import("ant-design-vue/es")["InputPassword"];
    AModal: typeof import("ant-design-vue/es")["Modal"];
    ARangePicker: typeof import("ant-design-vue/es")["RangePicker"];
    ASelect: typeof import("ant-design-vue/es")["Select"];
    ASpace: typeof import("ant-design-vue/es")["Space"];
    ASwitch: typeof import("ant-design-vue/es")["Switch"];
    ATooltip: typeof import("ant-design-vue/es")["Tooltip"];
    AUpload: typeof import("ant-design-vue/es")["Upload"];
    Layout: typeof import("./src/components/layout/index.vue")["default"];
    Notify: typeof import("./src/components/notify/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Sidebar: typeof import("./src/components/layout/sidebar.vue")["default"];
  }
}

export {};
